version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: islamdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d islamdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: [ "CMD", "/qdrant/healthcheck" ]
      interval: 5s
      timeout: 5s
      retries: 10

  embedder:
    build: ./embedder
    environment:
      MODEL_NAME: intfloat/multilingual-e5-base
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  backend:
    build: ./backend
    environment:
      PORT: "8080"
      POSTGRES_DSN: postgres://app:app@postgres:5432/islamdb?sslmode=disable
      QDRANT_HOST: qdrant
      QDRANT_GRPC_PORT: "6334"
      EMBEDDER_URL: http://embedder:8000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      embedder:
        condition: service_started

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  qdrant_storage:
